import { PrismaClient, JobSource, Recommendation, MatchStatus, LegitimacyTier, Seniority } from "@prisma/client";
import { generateDedupeKey } from "../lib/sources/dedupe";

const prisma = new PrismaClient();

// The demo jobs below carry placeholder apply URLs (job ids 101, 202, …).
// They exist to fill the feed before any real scan has run. Once a database
// holds real scanned postings they are just broken links in everyone's feed,
// so they are only seeded when explicitly asked for.
const SEED_DEMO_JOBS = process.env.SEED_DEMO_JOBS === "1";

async function main() {
  console.log("Seeding database...");
  if (!SEED_DEMO_JOBS) {
    console.log(
      "Skipping demo jobs/matches (set SEED_DEMO_JOBS=1 to include them).",
    );
  }

  // 1. Seed Dev User & Active Resume
  const devUser = await prisma.user.upsert({
    where: { id: "dev_user_1" },
    update: {
      email: "dev@example.com",
      firstName: "Dev",
      lastName: "User",
      onboardedAt: new Date(),
    },
    create: {
      id: "dev_user_1",
      clerkId: "user_dev_seed",
      email: "dev@example.com",
      firstName: "Dev",
      lastName: "User",
      onboardedAt: new Date(),
    },
  });

  const devResume = await prisma.resume.upsert({
    where: { id: "dev_resume_1" },
    update: {
      userId: devUser.id,
      label: "Main Engineering CV",
      fileName: "dev_resume_2026.pdf",
      mimeType: "application/pdf",
      sizeBytes: 1048576,
      pageCount: 2,
      rawText: "Full-Stack Software Engineer with 6 years experience in TypeScript, React, Next.js, Node.js, PostgreSQL, and distributed systems. Built high-scale SaaS products and REST/GraphQL APIs.",
      charCount: 215,
      parseStatus: "PARSED",
      parseSource: "PDF_PARSE",
    },
    create: {
      id: "dev_resume_1",
      userId: devUser.id,
      label: "Main Engineering CV",
      fileName: "dev_resume_2026.pdf",
      mimeType: "application/pdf",
      sizeBytes: 1048576,
      pageCount: 2,
      rawText: "Full-Stack Software Engineer with 6 years experience in TypeScript, React, Next.js, Node.js, PostgreSQL, and distributed systems. Built high-scale SaaS products and REST/GraphQL APIs.",
      charCount: 215,
      parseStatus: "PARSED",
      parseSource: "PDF_PARSE",
    },
  });

  await prisma.user.update({
    where: { id: devUser.id },
    data: { activeResumeId: devResume.id },
  });

  // 2. Define 10 Seed Jobs across sources
  const jobSeeds = [
    {
      id: "job_seed_01",
      source: JobSource.GREENHOUSE,
      sourceId: "gh-101",
      title: "Senior Full Stack Engineer",
      company: "Stripe",
      location: "Bengaluru, KA",
      countryCode: "IN",
      isRemote: false,
      seniority: Seniority.SENIOR,
      employmentType: "FULL_TIME",
      salaryMin: 3500000,
      salaryMax: 5000000,
      salaryCurrency: "INR",
      salaryPeriod: "YEARLY",
      applyUrl: "https://boards.greenhouse.io/stripe/jobs/101",
      descriptionText: "Join Stripe as a Senior Full Stack Engineer. Build high-reliability financial interfaces using TypeScript, React, Next.js, and PostgreSQL. 5+ years software engineering experience required.",
      raw: { source: "greenhouse", board: "stripe" },
    },
    {
      id: "job_seed_02",
      source: JobSource.LEVER,
      sourceId: "lev-202",
      title: "Lead Frontend Engineer",
      company: "Vercel",
      location: "Remote, India",
      countryCode: "IN",
      isRemote: true,
      seniority: Seniority.LEAD,
      employmentType: "FULL_TIME",
      salaryMin: 4500000,
      salaryMax: 6500000,
      salaryCurrency: "INR",
      salaryPeriod: "YEARLY",
      applyUrl: "https://jobs.lever.co/vercel/202",
      descriptionText: "Vercel is looking for a Lead Frontend Engineer to drive developer experience platforms. Deep expertise in Next.js App Router, Tailwind CSS, performance optimization, and Web Vitals required.",
      raw: { source: "lever", board: "vercel" },
    },
    {
      id: "job_seed_03",
      source: JobSource.ASHBY,
      sourceId: "ash-303",
      title: "Backend Engineer - Platform",
      company: "Linear",
      location: "Remote",
      countryCode: "US",
      isRemote: true,
      seniority: Seniority.MID,
      employmentType: "FULL_TIME",
      salaryMin: 120000,
      salaryMax: 160000,
      salaryCurrency: "USD",
      salaryPeriod: "YEARLY",
      applyUrl: "https://jobs.ashbyhq.com/linear/303",
      descriptionText: "Build realtime sync engines and high-concurrency Node.js microservices for Linear. Strong understanding of Postgres, Redis, and WebSockets required.",
      raw: { source: "ashby", board: "linear" },
    },
    {
      id: "job_seed_04",
      source: JobSource.ADZUNA,
      sourceId: "adz-404",
      title: "Software Engineer - Microservices",
      company: "Razorpay Inc.",
      location: "Bengaluru",
      countryCode: "IN",
      isRemote: false,
      seniority: Seniority.MID,
      employmentType: "FULL_TIME",
      salaryMin: 2200000,
      salaryMax: 3200000,
      salaryCurrency: "INR",
      salaryPeriod: "YEARLY",
      applyUrl: "https://adzuna.in/details/404",
      descriptionText: "Razorpay is seeking a Backend Software Engineer. Build fault-tolerant payment gateways with Golang, Node.js, and Distributed Caching systems.",
      raw: { source: "adzuna", ad_id: 404 },
    },
    {
      id: "job_seed_05",
      source: JobSource.JSEARCH,
      sourceId: "jsearch-505",
      title: "Staff Systems Engineer",
      company: "Cloudflare",
      location: "Mumbai, MH",
      countryCode: "IN",
      isRemote: false,
      seniority: Seniority.STAFF,
      employmentType: "FULL_TIME",
      salaryMin: 5500000,
      salaryMax: 8000000,
      salaryCurrency: "INR",
      salaryPeriod: "YEARLY",
      applyUrl: "https://jsearch.api/jobs/505",
      descriptionText: "Architect low-latency edge computing systems in Rust and C++. Requires 8+ years experience in systems programming and networking protocols.",
      raw: { source: "jsearch", job_id: "505" },
    },
    {
      id: "job_seed_06",
      source: JobSource.GREENHOUSE,
      sourceId: "gh-606",
      title: "Product Engineer - AI Tools",
      company: "Notion",
      location: "Remote, IN",
      countryCode: "IN",
      isRemote: true,
      seniority: Seniority.SENIOR,
      employmentType: "FULL_TIME",
      salaryMin: 4000000,
      salaryMax: 5800000,
      salaryCurrency: "INR",
      salaryPeriod: "YEARLY",
      applyUrl: "https://boards.greenhouse.io/notion/jobs/606",
      descriptionText: "Build AI-driven productivity features in Notion. Stack includes React, TypeScript, Node.js, Claude API, and vector embeddings.",
      raw: { source: "greenhouse", board: "notion" },
    },
    {
      id: "job_seed_07",
      source: JobSource.LEVER,
      sourceId: "lev-707",
      title: "Junior Web Developer",
      company: "Canva Limited",
      location: "Hyderabad",
      countryCode: "IN",
      isRemote: false,
      seniority: Seniority.JUNIOR,
      employmentType: "FULL_TIME",
      salaryMin: 1200000,
      salaryMax: 1800000,
      salaryCurrency: "INR",
      salaryPeriod: "YEARLY",
      applyUrl: "https://jobs.lever.co/canva/707",
      descriptionText: "Entry-level web developer role focusing on landing pages and accessibility compliance. Modern JavaScript, HTML5, CSS3, and React basics required.",
      raw: { source: "lever", board: "canva" },
    },
    {
      id: "job_seed_08",
      source: JobSource.SCRAPED,
      sourceId: "scr-808",
      title: "Rust Core Developer",
      company: "Solana Labs",
      location: "Remote",
      countryCode: "US",
      isRemote: true,
      seniority: Seniority.STAFF,
      employmentType: "CONTRACT",
      salaryMin: 140000,
      salaryMax: 190000,
      salaryCurrency: "USD",
      salaryPeriod: "YEARLY",
      applyUrl: "https://solana.com/careers/808",
      descriptionText: "Senior Rust engineer for Solana validator client performance tuning. Requires 5+ years of high-performance Rust and low-level concurrency.",
      raw: { source: "scraped", url: "https://solana.com" },
    },
    {
      id: "job_seed_09",
      source: JobSource.MANUAL,
      sourceId: "man-909",
      title: "Full Stack Developer",
      company: "Startup Co",
      location: "Delhi NCR",
      countryCode: "IN",
      isRemote: false,
      seniority: Seniority.MID,
      employmentType: "FULL_TIME",
      salaryMin: 1500000,
      salaryMax: 2500000,
      salaryCurrency: "INR",
      salaryPeriod: "YEARLY",
      applyUrl: "https://startup.example.com/apply",
      descriptionText: "Early-stage startup building AI e-commerce tools. Looking for generalist web developer with Next.js and Postgres experience.",
      raw: { source: "manual" },
    },
    {
      id: "job_seed_10",
      source: JobSource.ASHBY,
      sourceId: "ash-1010",
      title: "DevOps / Infrastructure Engineer",
      company: "Datadog GmbH",
      location: "Bengaluru",
      countryCode: "IN",
      isRemote: false,
      seniority: Seniority.SENIOR,
      employmentType: "FULL_TIME",
      salaryMin: 3800000,
      salaryMax: 5200000,
      salaryCurrency: "INR",
      salaryPeriod: "YEARLY",
      applyUrl: "https://jobs.ashbyhq.com/datadog/1010",
      descriptionText: "Manage Kubernetes clusters and Terraform infrastructure for cloud observability platform.",
      raw: { source: "ashby", board: "datadog" },
    },
  ];

  for (const seed of SEED_DEMO_JOBS ? jobSeeds : []) {
    const dedupeKey = generateDedupeKey({
      company: seed.company,
      title: seed.title,
      location: seed.location,
      isRemote: seed.isRemote,
    });

    await prisma.job.upsert({
      where: { id: seed.id },
      update: {
        source: seed.source,
        sourceId: seed.sourceId,
        dedupeKey,
        title: seed.title,
        company: seed.company,
        location: seed.location,
        countryCode: seed.countryCode,
        isRemote: seed.isRemote,
        seniority: seed.seniority,
        employmentType: seed.employmentType,
        descriptionText: seed.descriptionText,
        descriptionChars: seed.descriptionText.length,
        salaryMin: seed.salaryMin,
        salaryMax: seed.salaryMax,
        salaryCurrency: seed.salaryCurrency,
        salaryPeriod: seed.salaryPeriod,
        applyUrl: seed.applyUrl,
        raw: seed.raw,
      },
      create: {
        id: seed.id,
        source: seed.source,
        sourceId: seed.sourceId,
        dedupeKey,
        title: seed.title,
        company: seed.company,
        location: seed.location,
        countryCode: seed.countryCode,
        isRemote: seed.isRemote,
        seniority: seed.seniority,
        employmentType: seed.employmentType,
        descriptionText: seed.descriptionText,
        descriptionChars: seed.descriptionText.length,
        salaryMin: seed.salaryMin,
        salaryMax: seed.salaryMax,
        salaryCurrency: seed.salaryCurrency,
        salaryPeriod: seed.salaryPeriod,
        applyUrl: seed.applyUrl,
        raw: seed.raw,
      },
    });
  }

  // 3. Seed 10 Match rows spanning score bands (≥75, 50–74, <50, capped, pending)
  const matchSeeds = [
    // --- Band 1: High Match (≥75) ---
    {
      id: "match_seed_01",
      userId: devUser.id,
      jobId: "job_seed_01", // Stripe Senior Full Stack
      resumeId: devResume.id,
      status: MatchStatus.COMPLETE,
      score: 88,
      recommendation: Recommendation.APPLY,
      modelRecommendation: Recommendation.APPLY,
      dimRoleFit: 90,
      dimSkillsMatch: 88,
      dimExperienceDepth: 85,
      dimDomainContext: 88,
      dimLogistics: 90,
      summary: "Strong candidate alignment across full-stack TypeScript, React, Next.js, and relational databases. Meets all core senior requirements.",
      strengths: ["6 years TypeScript/React experience", "Proven track record with Next.js and PostgreSQL", "Location matches target city"],
      gaps: ["No direct financial API / payment gateway background mentioned"],
      cvTips: ["Highlight any high-throughput API design work in your current experience bullet points."],
      requirements: [
        { text: "5+ years software engineering experience", met: true, importance: "CRITICAL" },
        { text: "TypeScript & React expertise", met: true, importance: "CRITICAL" },
      ],
      legitimacyTier: LegitimacyTier.VERIFIED,
      legitimacySignals: { domainVerified: true, knownCompany: true },
      scoreCapApplied: null,
      evaluatedAt: new Date(),
    },
    {
      id: "match_seed_02",
      userId: devUser.id,
      jobId: "job_seed_02", // Vercel Lead Frontend
      resumeId: devResume.id,
      status: MatchStatus.COMPLETE,
      score: 82,
      recommendation: Recommendation.APPLY,
      modelRecommendation: Recommendation.APPLY,
      dimRoleFit: 85,
      dimSkillsMatch: 88,
      dimExperienceDepth: 78,
      dimDomainContext: 80,
      dimLogistics: 85,
      summary: "Excellent frontend alignment with Next.js and React. Candidate has strong remote history.",
      strengths: ["Extensive Next.js App Router experience", "Tailwind CSS expertise"],
      gaps: ["Lead experience is implicit rather than explicitly titled"],
      cvTips: ["Emphasize team leadership and architectural ownership."],
      requirements: [
        { text: "Next.js & React mastery", met: true, importance: "CRITICAL" },
      ],
      legitimacyTier: LegitimacyTier.VERIFIED,
      legitimacySignals: { domainVerified: true, verifiedCareerPage: true },
      scoreCapApplied: null,
      evaluatedAt: new Date(),
    },
    {
      id: "match_seed_03",
      userId: devUser.id,
      jobId: "job_seed_06", // Notion Product Engineer AI
      resumeId: devResume.id,
      status: MatchStatus.COMPLETE,
      score: 79,
      recommendation: Recommendation.APPLY,
      modelRecommendation: Recommendation.APPLY,
      dimRoleFit: 82,
      dimSkillsMatch: 80,
      dimExperienceDepth: 75,
      dimDomainContext: 78,
      dimLogistics: 80,
      summary: "Good technical overlap with TypeScript and modern product stack.",
      strengths: ["Strong web architecture background", "Node.js API expertise"],
      gaps: ["Limited explicit vector database / LLM fine-tuning experience in CV"],
      cvTips: ["Add details of recent AI integration work or prompt engineering projects."],
      requirements: [
        { text: "TypeScript / Node.js mastery", met: true, importance: "CRITICAL" },
      ],
      legitimacyTier: LegitimacyTier.VERIFIED,
      legitimacySignals: { domainVerified: true },
      scoreCapApplied: null,
      evaluatedAt: new Date(),
    },

    // --- Band 2: Mid Match (50–74) ---
    {
      id: "match_seed_04",
      userId: devUser.id,
      jobId: "job_seed_03", // Linear Backend Engineer
      resumeId: devResume.id,
      status: MatchStatus.COMPLETE,
      score: 68,
      recommendation: Recommendation.CONSIDER,
      modelRecommendation: Recommendation.CONSIDER,
      dimRoleFit: 70,
      dimSkillsMatch: 72,
      dimExperienceDepth: 65,
      dimDomainContext: 60,
      dimLogistics: 75,
      summary: "Decent backend alignment, though heavy frontend background means backend depth needs emphasis.",
      strengths: ["Node.js and PostgreSQL expertise"],
      gaps: ["No explicit WebSocket / realtime sync engine experience listed"],
      cvTips: ["Highlight experience with low-latency APIs and DB optimization."],
      requirements: [
        { text: "Postgres and Redis experience", met: true, importance: "HIGH" },
      ],
      legitimacyTier: LegitimacyTier.LIKELY_LEGITIMATE,
      legitimacySignals: { domainVerified: true },
      scoreCapApplied: null,
      evaluatedAt: new Date(),
    },
    {
      id: "match_seed_05",
      userId: devUser.id,
      jobId: "job_seed_04", // Razorpay Microservices
      resumeId: devResume.id,
      status: MatchStatus.COMPLETE,
      score: 62,
      recommendation: Recommendation.CONSIDER,
      modelRecommendation: Recommendation.CONSIDER,
      dimRoleFit: 65,
      dimSkillsMatch: 60,
      dimExperienceDepth: 65,
      dimDomainContext: 58,
      dimLogistics: 65,
      summary: "Moderate match. Role emphasizes Golang microservices while candidate primary language is TypeScript.",
      strengths: ["Distributed systems knowledge", "Node.js background"],
      gaps: ["Lacks Golang production experience"],
      cvTips: ["Include any polyglot backend projects or Go learning initiatives."],
      requirements: [
        { text: "Golang or Node.js microservices", met: true, importance: "HIGH" },
      ],
      legitimacyTier: LegitimacyTier.VERIFIED,
      legitimacySignals: { domainVerified: true },
      scoreCapApplied: null,
      evaluatedAt: new Date(),
    },
    {
      id: "match_seed_06",
      userId: devUser.id,
      jobId: "job_seed_09", // Startup Co Full Stack
      resumeId: devResume.id,
      status: MatchStatus.COMPLETE,
      score: 58,
      recommendation: Recommendation.CONSIDER,
      modelRecommendation: Recommendation.CONSIDER,
      dimRoleFit: 60,
      dimSkillsMatch: 65,
      dimExperienceDepth: 55,
      dimDomainContext: 50,
      dimLogistics: 60,
      summary: "Sufficient tech stack overlap, but salary band is below candidate expectation.",
      strengths: ["Next.js and Postgres capabilities"],
      gaps: ["Location requires Delhi NCR relocation"],
      cvTips: ["Confirm relocation readiness if applying."],
      requirements: [
        { text: "Next.js & Postgres", met: true, importance: "MEDIUM" },
      ],
      legitimacyTier: LegitimacyTier.UNVERIFIED,
      legitimacySignals: { startupListing: true },
      scoreCapApplied: null,
      evaluatedAt: new Date(),
    },

    // --- Band 3: Low Match (<50) ---
    {
      id: "match_seed_07",
      userId: devUser.id,
      jobId: "job_seed_05", // Cloudflare Staff Systems Engineer
      resumeId: devResume.id,
      status: MatchStatus.COMPLETE,
      score: 35,
      recommendation: Recommendation.SKIP,
      modelRecommendation: Recommendation.SKIP,
      dimRoleFit: 30,
      dimSkillsMatch: 35,
      dimExperienceDepth: 40,
      dimDomainContext: 30,
      dimLogistics: 40,
      summary: "Low alignment. Staff level systems engineering position requiring C++ and Rust networking.",
      strengths: ["General engineering experience"],
      gaps: ["Lacks C++/Rust systems programming background", "Below required seniority level (Staff)"],
      cvTips: ["Focus search on Senior Full-Stack or Web Frontend roles."],
      requirements: [
        { text: "8+ years systems programming in Rust/C++", met: false, importance: "CRITICAL" },
      ],
      legitimacyTier: LegitimacyTier.VERIFIED,
      legitimacySignals: { domainVerified: true },
      scoreCapApplied: null,
      evaluatedAt: new Date(),
    },
    {
      id: "match_seed_08",
      userId: devUser.id,
      jobId: "job_seed_07", // Canva Junior Web Developer
      resumeId: devResume.id,
      status: MatchStatus.COMPLETE,
      score: 42,
      recommendation: Recommendation.SKIP,
      modelRecommendation: Recommendation.SKIP,
      dimRoleFit: 40,
      dimSkillsMatch: 50,
      dimExperienceDepth: 35,
      dimDomainContext: 40,
      dimLogistics: 45,
      summary: "Role is significantly below candidate seniority (Junior vs Senior). High risk of being overqualified.",
      strengths: ["HTML/CSS/React proficiency"],
      gaps: ["Seniority mismatch (Junior role)"],
      cvTips: ["Target Mid to Senior engineering roles."],
      requirements: [
        { text: "Junior level experience", met: false, importance: "HIGH" },
      ],
      legitimacyTier: LegitimacyTier.VERIFIED,
      legitimacySignals: { domainVerified: true },
      scoreCapApplied: null,
      evaluatedAt: new Date(),
    },

    // --- Capped Match ---
    {
      id: "match_seed_09",
      userId: devUser.id,
      jobId: "job_seed_08", // Solana Rust Core Developer
      resumeId: devResume.id,
      status: MatchStatus.COMPLETE,
      score: 49,
      recommendation: Recommendation.SKIP,
      modelRecommendation: Recommendation.CONSIDER,
      dimRoleFit: 65,
      dimSkillsMatch: 70,
      dimExperienceDepth: 60,
      dimDomainContext: 55,
      dimLogistics: 65,
      summary: "Score capped at 49 due to missing critical requirement: 5+ years of high-performance Rust programming.",
      strengths: ["Distributed system interest", "Remote work history"],
      gaps: ["No Rust commercial experience on resume"],
      cvTips: ["Acquire Rust certifications or open-source commits before applying."],
      requirements: [
        { text: "5+ years high-performance Rust", met: false, importance: "CRITICAL" },
      ],
      legitimacyTier: LegitimacyTier.LIKELY_LEGITIMATE,
      legitimacySignals: { web3Project: true },
      scoreCapApplied: "Critical requirement missing: 5+ years Rust",
      evaluatedAt: new Date(),
    },

    // --- Pending Match ---
    {
      id: "match_seed_10",
      userId: devUser.id,
      jobId: "job_seed_10", // Datadog DevOps
      resumeId: devResume.id,
      status: MatchStatus.PENDING,
      triggerRunId: "trig_run_pending_1001",
      score: null,
      recommendation: null,
      modelRecommendation: null,
      dimRoleFit: null,
      dimSkillsMatch: null,
      dimExperienceDepth: null,
      dimDomainContext: null,
      dimLogistics: null,
      summary: null,
      strengths: null,
      gaps: null,
      cvTips: null,
      requirements: null,
      legitimacyTier: null,
      legitimacySignals: null,
      scoreCapApplied: null,
      evaluatedAt: null,
    },
  ];

  for (const match of SEED_DEMO_JOBS ? matchSeeds : []) {
    await prisma.match.upsert({
      where: { id: match.id },
      update: {
        userId: match.userId,
        jobId: match.jobId,
        resumeId: match.resumeId,
        status: match.status,
        triggerRunId: match.triggerRunId ?? null,
        score: match.score,
        recommendation: match.recommendation,
        modelRecommendation: match.modelRecommendation,
        dimRoleFit: match.dimRoleFit,
        dimSkillsMatch: match.dimSkillsMatch,
        dimExperienceDepth: match.dimExperienceDepth,
        dimDomainContext: match.dimDomainContext,
        dimLogistics: match.dimLogistics,
        summary: match.summary,
        strengths: match.strengths ?? undefined,
        gaps: match.gaps ?? undefined,
        cvTips: match.cvTips ?? undefined,
        requirements: match.requirements ?? undefined,
        legitimacyTier: match.legitimacyTier,
        legitimacySignals: match.legitimacySignals ?? undefined,
        scoreCapApplied: match.scoreCapApplied,
        evaluatedAt: match.evaluatedAt,
      },
      create: {
        id: match.id,
        userId: match.userId,
        jobId: match.jobId,
        resumeId: match.resumeId,
        status: match.status,
        triggerRunId: match.triggerRunId ?? null,
        score: match.score,
        recommendation: match.recommendation,
        modelRecommendation: match.modelRecommendation,
        dimRoleFit: match.dimRoleFit,
        dimSkillsMatch: match.dimSkillsMatch,
        dimExperienceDepth: match.dimExperienceDepth,
        dimDomainContext: match.dimDomainContext,
        dimLogistics: match.dimLogistics,
        summary: match.summary,
        strengths: match.strengths ?? undefined,
        gaps: match.gaps ?? undefined,
        cvTips: match.cvTips ?? undefined,
        requirements: match.requirements ?? undefined,
        legitimacyTier: match.legitimacyTier,
        legitimacySignals: match.legitimacySignals ?? undefined,
        scoreCapApplied: match.scoreCapApplied,
        evaluatedAt: match.evaluatedAt,
      },
    });
  }

  console.log("Seeding completed successfully!");
}

main()
  .catch((e) => {
    console.error("Seeding error:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
